
parameters:
    kw_parser.lexer.class: Kw\ParserBundle\Model\Lexer
    kw_parser.glrparser.class: Kw\ParserBundle\Model\GLRParser

services:
    kw_parser.lexer:
        class: %kw_parser.lexer.class%
        arguments: [ %kw_parser.cfg.terminals% ]

    kw_parser.glrparser:
        class: %kw_parser.glrparser.class%
        arguments: [ %kw_parser.parser.lrtables% ]

