
parameters:
    kw_parser.tokenFactory.class: Kw\ParserBundle\Model\SimpleTokenFactory
    kw_parser.lexer.class: Kw\ParserBundle\Model\SimpleLexer
    kw_parser.parser.class: Kw\ParserBundle\Model\GLRParser

    kw_parser.config:
        start: 'e'
        productions:
          e:
            - ['t']
            - ['e', 'T_PLUS', 't']
          t:
            - ['t', 'T_MULT', 'f']
            - ['f']
          f:
            - ['T_ID']
            - ['T_OPEN', 'e', 'T_CLOSE']

        terminals:
          T_PLUS: '\+'
          T_MULT: '\*'
          T_ID: 'id'
          T_OPEN: '\('
          T_CLOSE: '\)'

services:
    kw_parser.tokenFactory:
        class: %kw_parser.tokenFactory.class%

    kw_parser.lexer:
        class: %kw_parser.lexer.class%
        arguments: [ %kw_parser.cfg.terminals%, @kw_parser.tokenFactory ]

    kw_parser.parser:
        class: %kw_parser.parser.class%
        arguments: [ %kw_parser.parser.lrtables%, %kw_parser.parser.productions%, @kw_parser.tokenFactory ]





